version: '3.5'

services:
  phalcon-cphalcon:
    container_name: phalcon-cphalcon
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/cphalcon:/srv:rw
    ports:
      - "1999:88"
  phalcon-vokuro:
    container_name: phalcon-vokuro
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/vokuro:/srv:rw
    ports:
      - "2000:81"
  phalcon-api:
    container_name: phalcon-api
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/phalcon-api:/srv:rw
    ports:
      - "2001:82"
  phalcon-devtools:
    container_name: phalcon-devtools
    image: phalcon-local:4.0.5
    working_dir: /srv/
    volumes:
      - ./Projects/phalcon-devtools:/srv:rw
    ports:
      - "2002:83"
      - "2003:8000"
  phalcon-migrations:
    container_name: phalcon-migrations
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/migrations:/srv:rw
    ports:
      - "2004:89"
  phalcon-invo:
    container_name: phalcon-invo
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/invo:/srv:rw
    ports:
      - "2005:90"
  phalcon-incubator:
    container_name: phalcon-incubator
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/incubator:/srv:rw
    ports:
      - "2007:91"
  phalcon-incubator-acl:
    container_name: phalcon-incubator-acl
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/incubator-acl:/srv:rw
    ports:
      - "2008:92"
  phalcon-incubator-annotations:
    container_name: phalcon-incubator-annotations
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/incubator-annotations:/srv:rw
    ports:
      - "2009:93"
  phalcon-incubator-test:
    container_name: phalcon-incubator-test
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/incubator-test:/srv:rw
    ports:
      - "2010:94"
  phalcon-incubator-session:
    container_name: phalcon-incubator-session
    image: phalcon-local:4.0.5
    working_dir: /srv
    volumes:
      - ./Projects/incubator-session:/srv:rw
    ports:
      - "2010:94"
  phalcon-db-mysql:
    container_name: phalcon-db-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "phalcon"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3351:3306"
    volumes:
      - mysql-db:/var/lib/mysql
  phalcon-db-pgsql:
    container_name: phalcon-db-phsql
    image: postgres
    environment:
      POSTGRES_DB: "pg_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "3352:5432"
    volumes:
      - pgsql-db:/var/lib/postgresql
  phalcon-redis:
    container_name: phalcon-redis
    image: redis

networks:
  default:
    name: phalcon-local

volumes:
  mysql-db:
  pgsql-db:
